/**
 * Constants for the SIKU RV V2 UDP protocol.
 */
export const SIKU_DEFAULT_PORT = 4000;
export const SIKU_DEFAULT_PASSWORD = '1111';
export const SIKU_DEFAULT_DEVICE_ID = 'DEFAULT_DEVICEID';
export const SIKU_PACKET_PREFIX = Buffer.from([0xfd, 0xfd]);
export const SIKU_PROTOCOL_TYPE = 0x02;
export const SIKU_DEVICE_ID_LENGTH = 0x10;

export const SIKU_DISCOVERY_TIMEOUT_MS = 1_500;
export const SIKU_REQUEST_TIMEOUT_MS = 2_500;
export const SIKU_REQUEST_RETRY_DELAYS_MS = [0, 200, 500] as const;

export const SIKU_DISCOVERY_PARAMETERS = [0x007c, 0x00b9] as const;
export const SIKU_PARAMETER_POWER = 0x0001;
export const SIKU_PARAMETER_FAN_SPEED = 0x0002;
export const SIKU_PARAMETER_BOOST_STATUS = 0x0006;
export const SIKU_PARAMETER_TIMER_MODE = 0x0007;
export const SIKU_PARAMETER_TIMER_COUNTDOWN = 0x000b;
export const SIKU_PARAMETER_HUMIDITY_SENSOR_ENABLED = 0x000f;
export const SIKU_PARAMETER_RELAY_SENSOR_ENABLED = 0x0014;
export const SIKU_PARAMETER_ANALOG_SENSOR_ENABLED = 0x0016;
export const SIKU_PARAMETER_HUMIDITY_SETPOINT = 0x0019;
export const SIKU_PARAMETER_RTC_BATTERY_VOLTAGE = 0x0024;
export const SIKU_PARAMETER_HUMIDITY = 0x0025;
export const SIKU_PARAMETER_ANALOG_SENSOR_VALUE = 0x002d;
export const SIKU_PARAMETER_RELAY_SENSOR_VALUE = 0x0032;
export const SIKU_PARAMETER_MANUAL_FAN_SPEED = 0x0044;
export const SIKU_PARAMETER_FAN1_RPM = 0x004a;
export const SIKU_PARAMETER_FAN2_RPM = 0x004b;
export const SIKU_PARAMETER_FILTER_COUNTDOWN = 0x0064;
export const SIKU_PARAMETER_RESET_FILTER_TIMER = 0x0065;
export const SIKU_PARAMETER_BOOST_OVERRUN_MINUTES = 0x0066;
export const SIKU_PARAMETER_RTC_TIME = 0x006f;
export const SIKU_PARAMETER_RTC_CALENDAR = 0x0070;
export const SIKU_PARAMETER_TIME_CONTROLLED_OPERATION = 0x0072;
export const SIKU_PARAMETER_SCHEDULE = 0x0077;
export const SIKU_PARAMETER_DEVICE_ID = 0x007c;
export const SIKU_PARAMETER_OPERATING_HOURS = 0x007e;
export const SIKU_PARAMETER_RESET_ALARMS = 0x0080;
export const SIKU_PARAMETER_ALARM_LEVEL = 0x0083;
export const SIKU_PARAMETER_CLOUD_ENABLED = 0x0085;
export const SIKU_PARAMETER_FIRMWARE_VERSION = 0x0086;
export const SIKU_PARAMETER_FILTER_CHANGE_REQUIRED = 0x0088;
export const SIKU_PARAMETER_IP_ADDRESS = 0x00a3;
export const SIKU_PARAMETER_FAN_MODE = 0x00b7;
export const SIKU_PARAMETER_ANALOG_SENSOR_SETPOINT = 0x00b8;
export const SIKU_PARAMETER_DEVICE_TYPE = 0x00b9;
export const SIKU_PARAMETER_NIGHT_TIMER_SETPOINT = 0x0302;
export const SIKU_PARAMETER_PARTY_TIMER_SETPOINT = 0x0303;
export const SIKU_PARAMETER_HUMIDITY_SENSOR_STATE = 0x0304;
export const SIKU_PARAMETER_ANALOG_SENSOR_STATE = 0x0305;

export const SIKU_RUNTIME_POLL_PARAMETERS = [
    SIKU_PARAMETER_POWER,
    SIKU_PARAMETER_FAN_SPEED,
    SIKU_PARAMETER_DEVICE_ID,
    SIKU_PARAMETER_IP_ADDRESS,
    SIKU_PARAMETER_DEVICE_TYPE,
] as const;

export const SIKU_TIME_CHECK_PARAMETERS = [SIKU_PARAMETER_RTC_TIME, SIKU_PARAMETER_RTC_CALENDAR] as const;

export enum SikuFunction {
    Read = 0x01,
    Write = 0x02,
    ReadWrite = 0x03,
    Increment = 0x04,
    Decrement = 0x05,
    Response = 0x06,
}

export const SIKU_SPECIAL_COMMANDS = {
    changeFunction: 0xfc,
    unsupported: 0xfd,
    valueSize: 0xfe,
    page: 0xff,
} as const;
