version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: cron
      cronjob: "17 2 * * 2"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 15
    assignees:
      - ChrMaass
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: "41 2 * * 5"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 15
    assignees:
      - ChrMaass
